### ISSUE TITLE
t\nounverb.t does not fail *all* the time on Windows

### ISSUE THREAD

**Issue by nanis** [jjhart/insidesales_challenge#1]
The readme file states:

> Note - if you are on Windows, it will fail 100% of the time. Extra credit: why?

Just FYI, I do not see this.

<pre>C:\...\insidesales_challenge\Getopt> ver
Microsoft Windows [Version 6.3.9600]</pre>

<pre>C:\...\insidesales_challenge\Getopt> perl t\nounverb.t   
ok 1 - standard usage with arrayref transform                                       
ok 2 - standard usage with extra_opts (verbose)                                     
ok 3 - no noun nor verb died as expected                                            
ok 4 - no noun nor verb helptext correct                                            
ok 5 - bare help died as expected                                                   
ok 6 - bare help helptext correct                                                   
ok 7 - bare --help died as expected                                                 
ok 8 - bare --help helptext correct                                                 
ok 9 - unrecognized noun died as expected                                           
ok 10 - unrecognized noun helptext correct                                          
ok 11 - no verb died as expected                                                    
ok 12 - no verb helptext correct                                                    
ok 13 - noun help died as expected                                                  
ok 14 - noun help helptext correct                                                  
ok 15 - noun --help died as expected                                                
ok 16 - noun --help helptext correct                                                
ok 17 - noun w/ unrecognized verb died as expected                                  
ok 18 - noun w/ unrecognized verb helptext correct                                  
ok 19 - noun verb help died as expected                                             
ok 20 - noun verb help helptext correct                                             
ok 21 - noun verb --help died as expected                                           
ok 22 - noun verb --help helptext correct                                           
ok 23 - missing required parameter died as expected                                 
ok 24 - missing required parameter helptext correct                                 
1..24</pre>

<pre>C:\...> perl -V
Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
   
  Platform:
    osname=MSWin32, osvers=6.3, archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cl', ccflags ='-nologo -GF -W3 -O1 -Os -favor:INTEL64 -MD -Zi -DNDEBUG -GL -fp:precise -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIVE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE  -DUSE_64_BIT_ALL -DPERL_TEXTMODE_SCRIPTS -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO',
...</pre>

**Comment by jjhart** [comment]
Ah, thanks.  Updated the README.

Q: Do you get that result every time?

For your platform with the test consistently passing, I guess a more 
appropriate formulation of the question would be:

The perldoc for the "keys()" function specifies that the keys may be 
returned in any random order.  Assuming this to be true, stabilize the 
output of the helptext.

That's a bit more of a "hint" than the challenge should have, but no big 
deal =)

cheers,
John

**Comment by nanis** [comment]
No, the test fails once every few tries, as expected. I got curious because I could not see what about Windows would have made it fail **all** the time.

Not a bad way to test candidates given the number of questions on Stackoverflow about things coming out of hashes in the "wrong" order ;-)

Good luck.
